server:
  port: 8080

spring:
  application:
    name: rococo-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#    oauth2-use-pkce: true
#    display-request-duration: true
#    operations-sorter: alpha
#    doc-expansion: list
#    deep-linking: true
#    filter: true
#    security:
#      enable-csrf: false
#      show-in-open-api: true
#  openapi:
#    security:
#      bearerAuth:
#        type: http
#        scheme: bearer
#        bearer-format: JWT
#    paths-to-match: ["/**"]

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

rococo-front:
  base-uri: "http://127.0.0.1:3000"

rococo-artists:
  host: "127.0.0.1"
  port: 50001

rococo-museums:
  host: "127.0.0.1"
  port: 50002

rococo-paintings:
  host: "127.0.0.1"
  port: 50003

rococo-geos:
  host: "127.0.0.1"
  port: 50004

rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: 'docker'
  application:
    name: rococo-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://auth:9000"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#    oauth2-use-pkce: true
#    display-request-duration: true
#    operations-sorter: alpha
#    doc-expansion: list
#    deep-linking: true
#    filter: true
#    security:
#      enable-csrf: false
#      show-in-open-api: true
#  openapi:
#    security:
#      bearerAuth:
#        type: http
#        scheme: bearer
#        bearer-format: JWT
#    paths-to-match: ["/**"]

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

rococo-front:
  base-uri: "http://127.0.0.1:3000"

rococo-artists:
  host: "artists"
  port: 50001

rococo-museums:
  host: "museums"
  port: 50002

rococo-paintings:
  host: "paintings"
  port: 50003

rococo-geos:
  host: "geos"
  port: 50004

rococo-userdata:
  base-uri: 'http://userdata:8089'