create extension if not exists "pgcrypto";

create table if not exists "countries"
(
    id        varchar(255)  UNIQUE NOT NULL DEFAULT (gen_random_uuid()),
    name      varchar(255)  unique not null,
    primary key (id)
);


create table if not exists "geos"
(
    id        varchar(255)  UNIQUE NOT NULL DEFAULT (gen_random_uuid()),
    city      varchar(255)  unique not null,
    country_id  varchar(255)     not null,
    constraint fk_country_id foreign key (country_id) references "countries" (id),
    primary key (id)
);


insert into "countries" (id, name) values ('96a63542-860b-4c26-ae0f-d0f64954b72d', 'Австралия');
insert into "countries" (name) values ('Австрия');
insert into "countries" (name) values ('Азербайджан');
insert into "countries" (name) values ('Албания');
insert into "countries" (name) values ('Алжир');
insert into "countries" (name) values ('Ангола');
insert into "countries" (name) values ('Андорра');
insert into "countries" (name) values ('Антигуа и Барбуда');
insert into "countries" (name) values ('Аргентина');
insert into "countries" (name) values ('Армения');
insert into "countries" (name) values ('Афганистан');
insert into "countries" (name) values ('Багамские Острова');
insert into "countries" (name) values ('Бангладеш');
insert into "countries" (name) values ('Барбадос');
insert into "countries" (name) values ('Бахрейн');
insert into "countries" (name) values ('Белиз');
insert into "countries" (name) values ('Белоруссия');
insert into "countries" (name) values ('Бельгия');
insert into "countries" (name) values ('Бенин');
insert into "countries" (name) values ('Болгария');
insert into "countries" (name) values ('Боливия');
insert into "countries" (name) values ('Босния и Герцеговина');
insert into "countries" (name) values ('Ботсвана');
insert into "countries" (name) values ('Бразилия');
insert into "countries" (name) values ('Бруней');
insert into "countries" (name) values ('Буркина-Фасо');
insert into "countries" (name) values ('Бурунди');
insert into "countries" (name) values ('Бутан');
insert into "countries" (name) values ('Вануату');
insert into "countries" (name) values ('Великобритания');
insert into "countries" (name) values ('Венгрия');
insert into "countries" (name) values ('Венесуэла');
insert into "countries" (name) values ('Восточный Тимор');
insert into "countries" (name) values ('Вьетнам');
insert into "countries" (name) values ('Габон');
insert into "countries" (name) values ('Республика Гаити');
insert into "countries" (name) values ('Гайана');
insert into "countries" (name) values ('Гамбия');
insert into "countries" (name) values ('Гана');
insert into "countries" (name) values ('Гватемала');
insert into "countries" (name) values ('Гвинея');
insert into "countries" (name) values ('Гвинея-Бисау');
insert into "countries" (name) values ('Германия');
insert into "countries" (name) values ('Гондурас');
insert into "countries" (name) values ('Гренада');
insert into "countries" (name) values ('Греция');
insert into "countries" (name) values ('Грузия');
insert into "countries" (name) values ('Дания');
insert into "countries" (name) values ('Джибути');
insert into "countries" (name) values ('Доминика');
insert into "countries" (name) values ('Доминиканская Республика');
insert into "countries" (name) values ('Египет');
insert into "countries" (name) values ('Замбия');
insert into "countries" (name) values ('Зимбабве');
insert into "countries" (name) values ('Израиль');
insert into "countries" (name) values ('Индия');
insert into "countries" (name) values ('Индонезия');
insert into "countries" (name) values ('Иордания');
insert into "countries" (name) values ('Ирак');
insert into "countries" (name) values ('Иран');
insert into "countries" (name) values ('Ирландия');
insert into "countries" (name) values ('Исландия');
insert into "countries" (name) values ('Испания');
insert into "countries" (name) values ('Италия');
insert into "countries" (name) values ('Йемен');
insert into "countries" (name) values ('Кабо-Верде');
insert into "countries" (name) values ('Казахстан');
insert into "countries" (name) values ('Камбоджа');
insert into "countries" (name) values ('Камерун');
insert into "countries" (name) values ('Канада');
insert into "countries" (name) values ('Катар');
insert into "countries" (name) values ('Кения');
insert into "countries" (name) values ('Республика Кипр');
insert into "countries" (name) values ('Киргизия');
insert into "countries" (name) values ('Кирибати');
insert into "countries" (name) values ('Китай');
insert into "countries" (name) values ('Колумбия');
insert into "countries" (name) values ('Коморы');
insert into "countries" (name) values ('Республика Конго');
insert into "countries" (name) values ('Демократическая Республика Конго');
insert into "countries" (name) values ('Корейская Народно-Демократическая Республика');
insert into "countries" (name) values ('Республика Корея');
insert into "countries" (name) values ('Коста-Рика');
insert into "countries" (name) values ('Кот-д’Ивуар');
insert into "countries" (name) values ('Куба');
insert into "countries" (name) values ('Кувейт');
insert into "countries" (name) values ('Лаос');
insert into "countries" (name) values ('Латвия');
insert into "countries" (name) values ('Лесото');
insert into "countries" (name) values ('Либерия');
insert into "countries" (name) values ('Ливан');
insert into "countries" (name) values ('Ливия');
insert into "countries" (name) values ('Литва');
insert into "countries" (name) values ('Лихтенштейн');
insert into "countries" (name) values ('Люксембург');
insert into "countries" (name) values ('Маврикий');
insert into "countries" (name) values ('Мавритания');
insert into "countries" (name) values ('Мадагаскар');
insert into "countries" (name) values ('Малави');
insert into "countries" (name) values ('Малайзия');
insert into "countries" (name) values ('Мали');
insert into "countries" (name) values ('Мальдивы');
insert into "countries" (name) values ('Мальта');
insert into "countries" (name) values ('Марокко');
insert into "countries" (name) values ('Маршалловы Острова');
insert into "countries" (name) values ('Мексика');
insert into "countries" (name) values ('Федеративные Штаты Микронезии');
insert into "countries" (name) values ('Мозамбик');
insert into "countries" (name) values ('Молдавия');
insert into "countries" (name) values ('Монако');
insert into "countries" (name) values ('Монголия');
insert into "countries" (name) values ('Мьянма');
insert into "countries" (name) values ('Намибия');
insert into "countries" (name) values ('Науру');
insert into "countries" (name) values ('Непал');
insert into "countries" (name) values ('Нигер');
insert into "countries" (name) values ('Нигерия');
insert into "countries" (name) values ('Нидерланды');
insert into "countries" (name) values ('Никарагуа');
insert into "countries" (name) values ('Новая Зеландия');
insert into "countries" (name) values ('Норвегия');
insert into "countries" (name) values ('Объединённые Арабские Эмираты');
insert into "countries" (name) values ('Оман');
insert into "countries" (name) values ('Пакистан');
insert into "countries" (name) values ('Палау');
insert into "countries" (name) values ('Панама');
insert into "countries" (name) values ('Папуа — Новая Гвинея');
insert into "countries" (name) values ('Парагвай');
insert into "countries" (name) values ('Перу');
insert into "countries" (name) values ('Польша');
insert into "countries" (name) values ('Португалия');
insert into "countries" (name) values ('Россия');
insert into "countries" (name) values ('Руанда');
insert into "countries" (name) values ('Румыния');
insert into "countries" (name) values ('Сальвадор');
insert into "countries" (name) values ('Самоа');
insert into "countries" (name) values ('Сан-Марино');
insert into "countries" (name) values ('Сан-Томе и Принсипи');
insert into "countries" (name) values ('Саудовская Аравия');
insert into "countries" (name) values ('Флаг Северной Македонии');
insert into "countries" (name) values ('Сейшельские Острова');
insert into "countries" (name) values ('Сенегал');
insert into "countries" (name) values ('Сент-Винсент и Гренадины');
insert into "countries" (name) values ('Сент-Китс и Невис');
insert into "countries" (name) values ('Сент-Люсия');
insert into "countries" (name) values ('Сербия');
insert into "countries" (name) values ('Сингапур');
insert into "countries" (name) values ('Сирия');
insert into "countries" (name) values ('Словакия');
insert into "countries" (name) values ('Словения');
insert into "countries" (name) values ('Соединённые Штаты Америки');
insert into "countries" (name) values ('Соломоновы Острова');
insert into "countries" (name) values ('Сомали');
insert into "countries" (name) values ('Судан');
insert into "countries" (name) values ('Суринам');
insert into "countries" (name) values ('Сьерра-Леоне');
insert into "countries" (name) values ('Таджикистан');
insert into "countries" (name) values ('Таиланд');
insert into "countries" (name) values ('Танзания');
insert into "countries" (name) values ('Того');
insert into "countries" (name) values ('Тонга');
insert into "countries" (name) values ('Тринидад и Тобаго');
insert into "countries" (name) values ('Тувалу');
insert into "countries" (name) values ('Тунис');
insert into "countries" (name) values ('Туркменистан');
insert into "countries" (name) values ('Турция');
insert into "countries" (name) values ('Уганда');
insert into "countries" (name) values ('Узбекистан');
insert into "countries" (name) values ('Украина');
insert into "countries" (name) values ('Уругвай');
insert into "countries" (name) values ('Фиджи');
insert into "countries" (name) values ('Филиппины');
insert into "countries" (name) values ('Финляндия');
insert into "countries" (name) values ('Франция');
insert into "countries" (name) values ('Хорватия');
insert into "countries" (name) values ('Центральноафриканская Республика');
insert into "countries" (name) values ('Чад');
insert into "countries" (name) values ('Черногория');
insert into "countries" (name) values ('Чехия');
insert into "countries" (name) values ('Чили');
insert into "countries" (name) values ('Швейцария');
insert into "countries" (name) values ('Швеция');
insert into "countries" (name) values ('Флаг Шри-Ланки');
insert into "countries" (name) values ('Эквадор');
insert into "countries" (name) values ('Экваториальная Гвинея');
insert into "countries" (name) values ('Эритрея');
insert into "countries" (name) values ('Эсватини');
insert into "countries" (name) values ('Эстония');
insert into "countries" (name) values ('Эфиопия');
insert into "countries" (name) values ('Южно-Африканская Республика');
insert into "countries" (name) values ('Южный Судан');
insert into "countries" (name) values ('Ямайка');
insert into "countries" (name) values ('Япония');
insert into "countries" (name) values ('Ватикан');
insert into "countries" (name) values ('Палестина');

insert into "geos" (id, city, country_id) values ('578297a8-67af-436e-80b7-2bd0e41e66c8', 'TestGeoLocation', '96a63542-860b-4c26-ae0f-d0f64954b72d');
