grpc:
  port: 50001
spring:
  application:
    name: rococo-artists
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
  datasource:
     url: "jdbc:postgresql://127.0.0.1:5432/rococo-artists"
     hikari:
       connection-timeout: 20000
       minimum-idle: 10
       maximum-pool-size: 30
       idle-timeout: 10000
       max-lifetime: 1000
       auto-commit: true
     username: postgres
     password: secret
  flyway:
     enabled: true
     baseline-on-migrate: true
     baseline-version: 0
     schemas: public
     locations: classpath:db/migration/rococo-artists
  jpa:
     hibernate:
       ddl-auto: none
     properties:
       hibernate:
         jdbc:
           lob:
             non_contextual_creation: true
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     show-sql: false
     generate-ddl: false
     open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

---
grpc:
  port: 50001
spring:
  config:
    activate:
      on-profile: 'docker'
  application:
    name: rococo-artists
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://auth:9000"
  datasource:
    url: "jdbc:postgresql://rococo-db:5432/rococo-artists"
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: postgres
    password: secret
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rococo-artists
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG